$(document).ready(function(){
    $("#flip2").click(function(){
      $("#panel2").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip3").click(function(){
      $("#panel3").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip4").click(function(){
      $("#panel4").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip5").click(function(){
      $("#panel5").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip6").click(function(){
      $("#panel6").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip7").click(function(){
      $("#panel7").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip8").click(function(){
      $("#panel8").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip9").click(function(){
      $("#panel9").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip10").click(function(){
      $("#panel10").slideToggle("slow");
    });
  });

  $(document).ready(function(){
    $("#flip11").click(function(){
      $("#panel11").slideToggle("slow");
    });
  });

  $(document).ready(function(){
    $("#flip12").click(function(){
      $("#panel12").slideToggle("slow");
    });
  });

  $(document).ready(function(){
    $("#flip13").click(function(){
      $("#panel13").slideToggle("slow");
    });
  });

  $(document).ready(function(){
    $("#flip14").click(function(){
      $("#panel14").slideToggle("slow");
    });
  });

  $(document).ready(function(){
    $("#flip15").click(function(){
      $("#panel15").slideToggle("slow");
    });
  });

  $(document).ready(function(){
    $("#flip16").click(function(){
      $("#panel16").slideToggle("slow");
    });
  });

  $(document).ready(function(){
    $("#flip17").click(function(){
      $("#panel17").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip18").click(function(){
      $("#panel18").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip19").click(function(){
      $("#panel19").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip20").click(function(){
      $("#panel20").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip21").click(function(){
      $("#panel21").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip22").click(function(){
      $("#panel22").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip23").click(function(){
      $("#panel23").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip24").click(function(){
      $("#panel24").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip25").click(function(){
      $("#panel25").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip26").click(function(){
      $("#panel26").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip27").click(function(){
      $("#panel27").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip28").click(function(){
      $("#panel28").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip29").click(function(){
      $("#panel29").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip30").click(function(){
      $("#panel30").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip31").click(function(){
      $("#panel31").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip32").click(function(){
      $("#panel32").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip33").click(function(){
      $("#panel33").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip34").click(function(){
      $("#panel34").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip35").click(function(){
      $("#panel35").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip36").click(function(){
      $("#panel36").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip37").click(function(){
      $("#panel37").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip38").click(function(){
      $("#panel38").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip39").click(function(){
      $("#panel39").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip40").click(function(){
      $("#panel40").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip41").click(function(){
      $("#panel41").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $("#flip42").click(function(){
      $("#panel42").slideToggle("slow");
    });
  });